bgs/urls.py
from django.conf.urls import patterns, url
from bgs import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^view_project/(?P<project_id>.+)/$', views.view_project, name='view_project'),
    url(r'^edit_project/(?P<project_id>.+)/$', views.edit_project, name='edit_project'),
    url(r'^delete_project/(?P<project_id>.+)/$', views.delete_project, name='delete_project'),
    url(r'^download_project/(?P<project_id>.+)/$', views.download_project, name='download_project'),

    url( r'upload/', views.upload, name = 'jfu_upload' ),
    url( r'^delete/(?P<pk>\d+)$', views.upload_delete, name = 'jfu_delete' ),
    url(r'^view_uploaded_file/(?P<project_id>.+)/(?P<uploaded_file_id>\d+)$', views.view_uploaded_file, name='view_uploaded_file'),
    url(r'^poll_task_results/(?P<project_id>.+)/$', views.poll_task_results, name='poll_task_results'),
    url(r'^results/(?P<project_id>.+)/(?P<task_id>\d+)$', views.task_results, name='task_results'),
    url(r'^styled_graph/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/(?P<hash_code>.+)/(?P<image_type>.+)$', views.styled_graph, name='styled_graph'),
    url(r'^download_csv/(?P<project_id>.+)/(?P<csv_result_id>\d+)/$', views.download_csv, name='download_csv'),
    url(r'^styled_graph_editor/container/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/(?P<hash_code>.+)/$', views.styled_graph_editor, name='styled_graph_editor'),

    url(r'^create_combo/(?P<project_id>.+)/$', views.create_combo, name='create_combo'),
    url(r'^view_combo/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.view_combo, name='view_combo'),
    url(r'^save_combo_columns/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.save_combo_columns, name='save_combo_columns'),
    url(r'^delete_combo/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.delete_combo, name='delete_combo'),

    url(r'^combo/columns/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_columns, name='combo_columns'),
    url(r'^combo/graphs/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_graphs, name='combo_graphs'),
    url(r'^combo/view_grid(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_grid, name='combo_grid'),
    
    url(r'^combo/grid/handler/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_grid_handler, name='combo_grid_handler'),
    url(r'^combo/grid/cfg/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_grid_config, name='combo_grid_config'),
    url(r'^combo/grid/download/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.download_combo_dataframe, name='download_combo_dataframe'),

    url(r'^view_auto_combo/(?P<project_id>.+)/(?P<result_type>.+)/$', views.view_auto_combo, name='view_auto_combo'),
    url(r'^combo/auto/grid/handler/(?P<project_id>.+)/(?P<result_type>.+)/$', views.auto_combo_grid_handler, name='auto_combo_grid_handler'),
    url(r'^combo/auto/grid/cfg/(?P<project_id>.+)/(?P<result_type>.+)/$', views.auto_combo_grid_config, name='auto_combo_grid_config'),
    url(r'^combo/auto/grid/download/(?P<project_id>.+)/(?P<result_type>.+)/$', views.download_auto_combo_dataframe, name='download_auto_combo_dataframe'),

    url(r'^styled_graph_editor/editor_tab/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.graph_editor_tab, name='graph_editor_tab'),
    url(r'^category/category_tab/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.graph_category_tab, name='graph_category_tab'),
    url(r'^category/create/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.create_category, name='create_category'),
    url(r'^category/view/(?P<project_id>.+)/(?P<category_id>\d+)/$', views.view_category, name='view_category'),
    url(r'^category/delete/(?P<project_id>.+)/(?P<category_id>\d+)/$', views.delete_category, name='delete_category'),

    url(r'^category/samples_tab/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.graph_samples_tab, name='graph_samples_tab'),
    url(r'^category/view_samples/(?P<project_id>.+)/(?P<category_id>\d+)/$', views.view_graph_samples, name='view_graph_samples'),
    
    url(r'^lost_projects$', views.lost_projects, name='lost_projects'),
    url(r'^docs/(?P<doc_name>.+)/$', views.docs, name='docs'),

)

bgs/models.py
import StringIO
from collections import OrderedDict
from django.db import models
from django.db.models.aggregates import Min
from django.db.models.deletion import SET_NULL
import grp
import hashlib
from model_utils.managers import InheritanceManager
from operator import attrgetter
import os
import pickle
from pixelfields_smart_selects.db_fields import ChainedForeignKey
import stat

from bgs import genomics
from bgs.utils import matplotlib_utils
from bgs.utils.django_utils import delimited_file_has_header, \
    get_subclass_or_create
from bgs.utils.file_utils import get_extension, mk_path_for_file, mk_path, \
    name_from_file_name
from biographserv import settings
import pandas as pd
from reference_server.genomics import open_handle_gz
from reference_server.reference.igenomes_reference import IGenomesReference


class Organism(models.Model):
    species_name = models.CharField(max_length=256)
    common_name = models.CharField(max_length=256)
    def __unicode__(self):
        return "%s (%s)" % (self.species_name, self.common_name)

class AnnotationGroup(models.Model):
    name = models.CharField(max_length=256)
    def __unicode__(self):
        return self.name

class Build(models.Model):
    organism = models.ForeignKey(Organism)
    annotation_group = models.ForeignKey(AnnotationGroup)
    name = models.CharField(max_length=256)

    def get_igenomes_reference(self):
        return IGenomesReference(self.organism.species_name, self.annotation_group.name, self.name)

    def __unicode__(self):
        return "%s/%s" % (self.annotation_group, self.name)

class Project(models.Model):
    MAX_EMAIL_LENGTH=256
    uuid = models.CharField(max_length=32, primary_key=True)
    organism = models.ForeignKey(Organism, null=True)
#    annotation_group = models.ForeignKey(AnnotationGroup, null=True)
    build = ChainedForeignKey(Build,
                              chained_field='organism',
                              chained_model_field='organism',
                              show_all=False,
                              auto_choose=True,
                              null=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    email = models.CharField(max_length=MAX_EMAIL_LENGTH)
    read_only = models.BooleanField(default=False)
    
    @property
    def date(self):
        # Earliest uploaded file
        return self.uploadedfile_set.all().aggregate(Min('date')).values()[0]

    def get_combos(self):
        combo_dicts = []
        for (combo_id, name) in self.combo_set.all().order_by("id").values_list("id", "name"):
            combo_data = {"id" : combo_id, "name" : name}
            combo_dicts.append(combo_data)
        return combo_dicts

    def create_default_genomic_ranges(self):
        GenomicRange.objects.create(project=self,
                                name='Promoter',
                                anchor=GenomicAnchor.TSS,
                                upstream=1000,
                                downstream=1000,
                                max_size=3000,
                                step_size=100,)

        GenomicRange.objects.create(project=self,
                                    name='Gene Body',
                                    anchor=GenomicAnchor.GENE_START_END,
                                    upstream=0,
                                    downstream=0,
                                    max_size=20000,
                                    step_size=500,)


    def __unicode__(self):
        name = self.name or self.pk
        if self.build:
            name = "%s (%s)" % (name, self.build)
        return name


class ComboType(object):
    REGION_STATS = 'R'
    GENES = 'G'
    OTHER = 'O'
    COMBO_TYPE_CHOICE = (
        (REGION_STATS, 'Region Stats'),
        (GENES, 'Genes'),
        (OTHER, 'Other'),
    )

class Combo(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=100)
    combo_type = models.CharField(max_length=1, choices=ComboType.COMBO_TYPE_CHOICE, null=True, blank=True)
    file_name = models.TextField()
    
    def get_columns(self):
        if self.combo_type is None:
            return ([], []) 
        
        csv_results_qs = CSVResult.get_for_project(self.project)
        if self.combo_type == ComboType.REGION_STATS:
            columns_qs = csv_results_qs.filter(result_type=CSVResultType.REGION_STATS)
        else:
            result_types = [CSVResultType.GENE_SCORES]
            result_types.extend(CSVResultType.UPLOADED_CSVRESULTS)
            columns_qs = csv_results_qs.filter(result_type__in=result_types)
        
        selected_column_ids = self.combocolumn_set.all().values_list("csv_result_id", flat=True)
        selected_columns = CSVResult.objects.filter(id__in=selected_column_ids).order_by("combocolumn__sort_order")
        available_columns = columns_qs.exclude(id__in=selected_column_ids)
        return (available_columns, selected_columns)

    def get_dataframe(self):
        dataframes = []
        for cc in self.combocolumn_set.all().order_by("sort_order"):
            cc_df = cc.csv_result.get_dataframe()
            dataframes.append(cc_df)
            
        df = pd.concat(dataframes, axis=1)
        return df

    def get_column_types_and_homogeneity(self):
        ''' returns (num_column_types, distinct_column_types, is_homogenous) '''

        mappings = get_csv_result_type_mappings()
        column_types = list(self.combocolumn_set.all().values_list('csv_result__result_type', flat=True))

        num_column_types = len(column_types)
        distinct_column_types = set(mappings[t] for t in column_types) 
        is_homogenous = len(distinct_column_types) <= 1

        return (num_column_types, distinct_column_types, is_homogenous)
        
    def is_multi_expression(self):
        (num_column_types, distinct_column_types, is_homogenous) = self.get_column_types_and_homogeneity()
        return num_column_types > 1 and is_homogenous and "Expression" in distinct_column_types

    
    def __unicode__(self):
        return "Combo: %s%s" % (self.name or '', self.project)

class GenomicAnchor(object):
    TSS = 'P'
    GENE_START_END = 'G'
    GENOMIC_ANCHOR_CHOICE = (
        (TSS, 'TSS'),
        (GENE_START_END, 'Gene Start/End')
    )

class GenomicRange(models.Model):
    project = models.ForeignKey(Project)
    name = models.TextField()
    anchor = models.CharField(max_length=1, choices=GenomicAnchor.GENOMIC_ANCHOR_CHOICE)
    upstream = models.IntegerField()
    downstream = models.IntegerField()
    max_size = models.IntegerField()
    step_size = models.IntegerField()


def get_processing_dir(project_id):
    processing_dir = os.path.join(settings.PROCESSOR_OUTPUT_DIR, str(project_id))
    mk_path(processing_dir)
    posix_stat = os.stat(processing_dir)

    if settings.GROUP_NAME:
        try:
            uid = posix_stat.st_uid
            gid = grp.getgrnam(settings.GROUP_NAME).gr_gid
    #        print "Changing permissions:"
            os.chown(processing_dir, uid, gid)
    #        print "Changing group ownership:"
            os.chmod(processing_dir, posix_stat.st_mode | stat.S_IWGRP)
        except Exception as e:
            print e # Ignore
#    posix_stat = os.stat(processing_dir)
#    mode = posix_stat.st_mode
    
#    print "%s mode: %d" % (processing_dir, mode)
#    if not stat.S_IWGRP & mode:
#        print "Not writable by GROUP" 
#    if not stat.S_IWOTH & mode:
#        print "Not writable by others" 
    
    return processing_dir

class UploadedFileTypes(object):
    BED = 'B'
    VCF = 'V'
    CUFFDIFF = 'C'
    EXPRESSION = 'E'
    SINGLE_SAMPLE_EXPRESSION = 'S'
    MULTI_SAMPLE_EXPRESSION = 'M'
    UPLOADED_FILES_CHOICE = (
        (BED, 'BED'),
        (VCF, 'VCF'),
        (CUFFDIFF, 'CuffDiff'),
        (SINGLE_SAMPLE_EXPRESSION, 'Expression (single sample)'),
        (MULTI_SAMPLE_EXPRESSION, 'Expression (multi-sample)'),
    )

    EXTENSIONS = {BED : ['bed', 'broadPeak', 'narrowPeak'],
                  VCF : ['vcf'],
                  EXPRESSION : ['tsv', 'csv'],
                  CUFFDIFF : ['diff']}

    REQUIRES_REFERENCE = {BED}
    REQUIRES_GENOMIC_RANGES = {BED}

    @classmethod
    def get_file_type_from_extension(cls, uploaded_file):
        extension_lookup = cls.get_extension_lookup()

        filename = uploaded_file.name
        filename, open_file = genomics.handle_open_file_gzip(filename, uploaded_file.file)
        ext = get_extension(filename)
        try:
            file_type = extension_lookup[ext]
        except KeyError as e:
            print e
            msg = "Can't handle files with extension '%s'" % ext
            raise ValueError(msg)
            
        if file_type == UploadedFileTypes.EXPRESSION:
            file_type = cls.determine_expression_type(filename, open_file) 
        
        return file_type

    @classmethod
    def get_extension_lookup(cls):
        extension_lookup = {}
        for (file_type, extensions) in cls.EXTENSIONS.iteritems():
            for ext in extensions:
                extension_lookup[ext] = file_type
        return extension_lookup

    @classmethod
    def determine_expression_type(cls, file_name, open_file):
        (has_header, num_columns, _) = delimited_file_has_header(open_file)
        if num_columns == 2 and not has_header:
            return cls.SINGLE_SAMPLE_EXPRESSION
        elif num_columns > 2 and has_header:
            return cls.MULTI_SAMPLE_EXPRESSION
        
        msg = "Could not determine expression type of %s header: %s, columns: %d" % (file_name, has_header, num_columns)
        raise ValueError(msg)

    @classmethod
    def requires_reference(cls, uploaded_file_type):
        return uploaded_file_type in cls.REQUIRES_REFERENCE


class UploadedFile(models.Model):
    project = models.ForeignKey(Project)
    name = models.TextField()

bgs/templates/bgs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}BioGraphServ{% endblock %}</title>
	<script type="text/javascript" src="/static/js/lib/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery-ui-1.11.2.custom/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery.layout.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery.form.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery.xcolor.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery.colorPicker.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/prettyPhoto_compressed_3.1.5/js/jquery.prettyPhoto.js"></script>

	<link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon.ico" />
	<link href="/static/js/lib/jquery-ui-1.11.2.custom/jquery-ui.min.css" rel="stylesheet">
	<link href="/static/css/colorPicker.css"" rel="stylesheet"></link>
	<link rel="stylesheet" href="/static/js/lib/prettyPhoto_compressed_3.1.5/css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
	<link href="/static/css/menu-top.css" rel="stylesheet">
	<link href="/static/css/biographserv.css" rel="stylesheet">

	<style type="text/css">
	html, body {
		width:		100%;
		height:		100%;
		padding:	0;
		margin:		0;
	}

	div#content {
		width:		100%;
		height:		100%;					
		padding:	0;
		margin:		0;
		overflow: auto;
	}
	{% block css %}{% endblock %}
	</style>

	<script type="text/javascript">
		{% block jshead %}{% endblock %}
		$(document).ready(function () {
			$('body').layout({
				north: {
					resizeable: false,
					size: 30,
				}
			});

		    {% block jsdocumentready %}{% endblock %}
		});
	</script>

	<!-- head block -->
    {% block head %}{% endblock %}
	<!-- /head block -->
</head>

<body>
	<div id="siteMenuBar" class='ui-layout-north'>
		<div id="menuContainer" class="ui-widget-header">
			<ul>
				<li><a href="/"><div class='biographserv-logo'></div></a></li>
				<li><a href="{% url 'docs' 'doc_index' %}">Docs</a></li>
				<li><a href="{% url 'view_project' 'sample_project' %}">Sample Data</a></li>
			</ul>
		</div>
	</div>
    <div id="content" class='ui-layout-center'>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

bgs/templates/bgs/combo_columns.html
<style>
.connectedSortable {
	min-height: 50px;
}

#columns-widget ul
{
	list-style-type: none;
}

#columns-widget li
{
	display: inline-block;
	margin: 0;
	padding: 0 5px 0 5px;
	margin-right: 10px;
	border: 1px solid #eee;
}
</style>

<script>
	function save_combo_columns() {
		var csv_result_ids = [];
		$("li", "ul#selected_columns_sortable").each(function() {
			csv_result_ids.push($(this).attr("csv_result_id"));
		});
		
		var data = 'csrfmiddlewaretoken={{ csrf_token }}&csv_result_ids=' + encodeURIComponent(JSON.stringify(csv_result_ids));
		console.log(data);
		$.ajax({
		    type: "POST",
		    data: data,
		    url: "{% url 'save_combo_columns' project.pk combo.pk %}",
		    success: function() {
				$("#unsaved-columns-message").hide();
				$("#columns-save-message").fadeIn(function() { $(this).fadeOut(1500); });
		    },
		});
	}


	$(document).ready(function() {
		$("button.save-button").button({
			icons: {primary: "ui-icon-disk"},
	    });

		$(".connectedSortable").sortable({
		    items: "li.user_column",
		    placeholder: "sort_placeholder",
		    connectWith: '.connectedSortable',
		}).disableSelection();

		$("#selected_columns_sortable").bind("sortupdate", function(event, ui) {
			$("#unsaved-columns-message").fadeIn();
			console.log("Updated!");
		});
		
		$('#save-columns').click(save_combo_columns);
		
	});
</script>
<div>
	Drag and drop the columns in your desired order, save then view the grid. 

	<div id="columns-widget">
		<div id="available_columns">
		    <h2>Available Columns</h2>
			<ul id="available_columns_sortable" class="ui-widget-header connectedSortable">
				{% for column in available_columns %}
				    <li class="ui-state-default user_column" id="{{ column }}" csv_result_id={{ column.pk }}>{{ column }}</li>
			    {% endfor %}
			</ul>
		</div>
		<div id="my_columns">
			<h2>My Columns</h2>
			<ul id="selected_columns_sortable" class="ui-widget-header connectedSortable">
				{% for column in selected_columns %}
				    <li class="ui-state-default user_column" id="{{ column }}" csv_result_id={{ column.pk }}>{{ column }}</li>
			    {% endfor %}
			</ul>
		</div>

		<button id='save-columns' class='save-button'>save</button>
		<span id='unsaved-columns-message' style='display: none'>Warning: Unsaved column changes.</span>
		<span id='columns-save-message' style='display: none'>Saved Successfully</span>
	</div>
</div>

bgs/templates/bgs/combo_graphs.html
{% extends "bgs/view_uploaded_file.html" %}

{% block content_above_tasks %}
{# Empty on purpose #}
{% endblock %}

bgs/templates/bgs/view_combo.html
<style>
.connectedSortable {
	min-height: 50px;
}

#columns-widget ul
{
	list-style-type: none;
}

#columns-widget li
{
	display: inline-block;
	margin: 0;
	padding: 0 5px 0 5px;
	margin-right: 10px;
	border: 1px solid #eee;
}

</style>

<script>
	function save_combo_columns() {
		var csv_result_ids = [];
		$("li", "ul#selected_columns_sortable").each(function() {
			csv_result_ids.push($(this).attr("csv_result_id"));
		});
		
		var data = 'csrfmiddlewaretoken={{ csrf_token }}&csv_result_ids=' + encodeURIComponent(JSON.stringify(csv_result_ids));
		console.log(data);
		$.ajax({
		    type: "POST",
		    data: data,
		    url: "{% url 'save_combo_columns' project.pk combo.pk %}",
		    success: function() {
				$("#unsaved-columns-message").hide();
				$("#columns-save-message").fadeIn(function() { $(this).fadeOut(1500); });
		    },
		});
	}


	$(document).ready(function() {
		$("button.save-button").button({
			icons: {primary: "ui-icon-disk"},
	    });

		var options	= {
			target: '#view-combo',
			success: function() {
				if ($(".errorlist", "form#project-form").length == 0) { // success
					$("#save-message").fadeIn(function() { $(this).fadeOut(1500); });

					var name = $("#id_name", "#combo-form").val();
					var combo = get_combo_row( {{ combo.pk }} );
					$("a", combo).text(name)
				}
			},
		};
			
		$('form#combo-form').ajaxForm(options); 

		///
		$(".connectedSortable").sortable({
		    items: "li.user_column",
		    placeholder: "sort_placeholder",
		    connectWith: '.connectedSortable',
		}).disableSelection();

		$("#selected_columns_sortable").bind("sortupdate", function(event, ui) {
			$("#unsaved-columns-message").fadeIn();
			console.log("Updated!");
		});
		
		$('#save-columns').click(save_combo_columns);
		
		$('#combo-tabs').tabs();
		
	});
</script>
<div id='view-combo'>
	<form id='combo-form' method="post" action="{{ request.path }}">
        {% csrf_token %}
		<table>
			{% for field in form %}
			<tr>
				<td>
				{% if field.field.required %}
				<span class="label"><span class="required">{{ field.label }}</span></span>
		        {% else %}
		        <span class="label">{{ field.label }}</span>
		        {% endif %}
				<td>{{ field.errors }}
					{{ field }}
			</tr>
			{% endfor %}
			<tr>
				<td>
				<button id='save-combo' class='save-button'>save</button>
				<td>
				<span id='save-message' style='display: none'>Saved Successfully</span>
			</tr>
		</table>
	</form>

	<div>
	{% if combo.combo_type %}
		<div id="combo-tabs"> 
		    <ul> 
		        <li><a href="{% url 'combo_columns' project.pk combo.pk %}">Columns</a></li> 
		        <li><a href="{% url 'combo_grid' project.pk combo.pk %}">Grid</a></li> 
		        <li><a href="{% url 'combo_graphs' project.pk combo.pk %}">Graphs</a></li> 
		    </ul>
		</div>​​​​​​​​​​
	{% else %}
		Please select a combo type		
	{% endif %}

	</div>

</div>

bgs/templates/bgs/view_uploaded_file.html
{% extends "bgs/base_task_poller.html" %}

{% block add_task_results %}
		$.each(task_results, function (taskId, data) {
			var base_url = "{% url 'task_results' project.pk 9999999999 %}";
			var url = base_url.replace(9999999999, taskId);

			var resultDiv = $("<div id='result'></div>");
			resultDiv.hide();
			$("#results").prepend(resultDiv);
			resultDiv.load(url, function() {
				initialiseResult(resultDiv);
				resultDiv.fadeIn()
			});
		});
		task_results = {};
{% endblock %}

{% block jshead %}
	function initialiseStyleToolkit(ppSelector) {
		var imageSelector = $(".generated-image", ppSelector);
		var styled_graph_id = imageSelector.attr("styled_graph_id");
		var styled_graph_hash_code = $(imageSelector).attr("styled_graph_hash_code");

		var base_url = "{% url 'styled_graph_editor' project.pk 9999999999 'HASH_CODE_PLACEHOLDER' %}";
		var url = base_url.replace(9999999999, styled_graph_id);
		url = url.replace('HASH_CODE_PLACEHOLDER', styled_graph_hash_code);

		// JQuery UI layout setup
		var editorContainer = $(".styled-graph-editor-container", ppSelector);
		var imageContainer = $(".toolkit-image-container", ppSelector);

		var parent_h = ppSelector.parent().height();
		var PADDING = 0;
		ppSelector.height(parent_h - PADDING);
		ppSelector.layout({
			west: {
				resizeable: false,
				size: 450,
			}
		});
		editorContainer.load(url);
	}

	function initialiseResult(resultsSelector) {
		$(".image-container", resultsSelector).hover(
			function() {
				$(".overlay-background", this).stop().animate({"opacity": "0.6"}, 350);
				$(".overlay-buttons", this).stop().animate({"opacity": "1"}, 350);
			},
			function() {
				$(".overlay-background", this).stop().animate({"opacity": "0"}, 350);
				$(".overlay-buttons", this).stop().animate({"opacity": "0"}, 350);
		});

		var buttons_selector = $(".download-image-button", resultsSelector);
		buttons_selector.button({
	      icons: {
	        primary: "ui-icon-arrowthickstop-1-s"
	      }
	    });

		// Attach download links for each image type to each graph
		$(".image-container", resultsSelector).each(function() {
			var container = this;
			var resultImage = $("img.generated-image", container);
			var styled_graph_id = resultImage.attr("styled_graph_id");

			var IMAGE_TYPES = ['eps', 'pdf', 'svg', 'tif'];
			$(IMAGE_TYPES).each(function() {
				var image_type = this;
				$("button." + image_type + "-image-link", container).click(function() {
					// Hash code may have changed, so need to get it again
					var styled_graph_hash_code = resultImage.attr("styled_graph_hash_code");
		
					var base_url = "{% url 'styled_graph' project.pk 9999999999 'HASH_CODE_PLACEHOLDER' 'IMAGE_TYPE_PLACEHOLDER' %}";
					base_url = base_url.replace(9999999999, styled_graph_id);
					base_url = base_url.replace('HASH_CODE_PLACEHOLDER', styled_graph_hash_code);
					var url = base_url.replace("IMAGE_TYPE_PLACEHOLDER", image_type);
					window.location = url;
				});  
			});
		});
		
		$("a[rel^='prettyPhoto']", resultsSelector).prettyPhoto({
			inline_markup: '<div class="my_pp_inline">{content}</div>',
			social_tools: false,
			changepicturecallback: function(){
				var ppSelector = $(".my_pp_inline");
				initialiseStyleToolkit(ppSelector);
			},
		});
	}
	
	function changeUploadedName() {
		if ($(".errorlist", "form#name-form").length == 0) { // success
			$("#save-message").fadeIn(function() { $(this).fadeOut(1500); });
	
			var name = $("#id_name", "#name-form").val();
			get_uploaded_file_link({{ uploaded_file.pk }}).text(name);
		}
	}
	
{% endblock %}


{% block jsdocumentready %}
		initialiseResult($("#results")); // do for all

		var options	= {
			target: '#view-uploaded-file',
			complete: changeUploadedName, // success isn't being called (not sure why) - we check for errors in this function
		};
			
		$('form#name-form').ajaxForm(options); 

		$("button#save-uploaded-file").button({
			icons: {primary: "ui-icon-disk"},
	    });
{% endblock %}

{% block content_above_tasks %}
	<form id='name-form' method="post" action="{{ request.path }}">
        {% csrf_token %}
	<h3>Uploaded File: {{ name_form.name }}<button id='save-uploaded-file'>save</button> </h3> 
	<span id='save-message' style='display: none'>Saved Successfully</span>
	</form>
{% endblock %}

{% block content_below_tasks %}
	<div id='results'>
		{% include 'bgs/results.html' %}
	</div>
{% endblock %}
	    